apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  labels:
    app: kratos
    service: discord-bot
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: kratos
      service: discord-bot
  template:
    metadata:
      name: discord-bot
      labels:
        app: kratos
        service: discord-bot
    spec:
      containers:
        - name: bot
          image: gcr.io/kratos-201621/discord-bot:b745ead6
          resources:
            limits:
              cpu: "100m"
              memory: 100M
            requests:
              cpu: "10m"
              memory: 50M
          env:
            - name: BUGSNAG_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kratos-bugsnag
                  key: token
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord
                  key: token
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          readinessProbe:
            exec:
              command:
                - cat
                - /tmp/ready
            initialDelaySeconds: 2
            periodSeconds: 1
          livenessProbe:
            exec:
              command:
                - cat
                - /tmp/health
            periodSeconds: 4
            initialDelaySeconds: 5