apiVersion: v1
kind: Service
metadata:
  name: message-recovery-api
  labels:
    app: kratos
    service: message-recovery
    tier: api
spec:
  selector:
    app: kratos
    service: message-recovery
    tier: api
  ports:
    - port: 80
      targetPort: http
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-recovery-api
  labels:
    app: kratos
    service: message-recovery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kratos
      service: message-recovery
  template:
    metadata:
      name: message-recovery-api
      labels:
        app: kratos
        service: message-recovery
        tier: api
    spec:
      containers:
        - name: api
          image: outdatedversion/kratos-message-recovery-service:f74910a5
          ports:
            - containerPort: 2000
              name: http