apiVersion: v1
kind: Service
metadata:
  name: message-recovery-api
  labels:
    app: kratos
    service: message-recovery
    tier: api
spec:
  selector:
    app: kratos
    service: message-recovery
    tier: api
  ports:
    - port: 80
      targetPort: http
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-recovery-api
  labels:
    app: kratos
    service: message-recovery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kratos
      service: message-recovery
  template:
    metadata:
      name: message-recovery-api
      labels:
        app: kratos
        service: message-recovery
        tier: api
    spec:
      imagePullSecrets:
          - name: outdatedversion-private-registry
      containers:
        - name: api
          image: docker-registry.outdatedversion.com/kratos/message-recovery-service:796eeab0
          ports:
            - containerPort: 2000
              name: http
          readinessProbe:
            httpGet:
              path: /_ready
              port: 2000
            initialDelaySeconds: 5
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /_health
              port: 2000
            periodSeconds: 1
            initialDelaySeconds: 1