apiVersion: v1
kind: Service
metadata:
  name: message-recovery-nginx
  labels:
    app: kratos
    service: message-recovery
    tier: distribution
spec:
  ports:
    - port: 80
  selector:
    app: kratos
    service: message-recovery
    tier: distribution
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mr-content-pv-claim
  labels:
    app: kratos
    service: message-recovery
    tier: distribution
spec:
  accessModes: 
    - ReadOnlyMany
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-recovery-nginx
  labels:
    app: kratos
    service: message-recovery

# TODO(ben): Deployment needs to be completed + look over PV claim